- .github/workflows/ci.yml
> Disable stable build in GHA

- aiidalab_ispg/widgets.py
> Download button downloads all conformes

- aiidalab_ispg/widgets.py
> Simple WorkChain viewer

- README.md
- setup.cfg
The cclib dependency will be fully specified by aiida-orca.
> Update cclib to 1.7.2

- aiidalab_ispg/parameters/orca.yaml
- aiidalab_ispg/steps.py
Closes #30 
Also use `orca@slurm` computer by default.
> Configurable number of excited states

- aiidalab_ispg/__init__.py
- aiidalab_ispg/qeapp/README
- aiidalab_ispg/qeapp/process.py
- aiidalab_ispg/qeapp/structures.py
- aiidalab_ispg/qeapp/widgets.py
- aiidalab_ispg/steps.py
- aiidalab_ispg/structures.py
- aiidalab_ispg/utils.py
- aiidalab_ispg/widgets.py
- atmospec.ipynb
- example.ipynb
- workflow_workspace.ipynb
- workflows/aiidalab_atmospec_workchain/__init__.py
- Switch NodeViewWidget to AiidaNodeViewWidget
- Go through files copied over from aiidalab-qe. Compare with the current version, remove unneeded stuff. Stuff that is common to both aiidalab-ispg and aiidalab-qe should live in a separate well-defined files so that I can pull in improvements reasonably easily (and vice versa, I can submit patches as well).
Partly solves #31
> Cleanup widgets

- aiidalab_ispg/spectrum.py
- aiidalab_ispg/steps.py
- workflows/aiidalab_atmospec_workchain/__init__.py
There was a missing conversion factor from a.u. to eV so the intensity was off by 27x. Fixes #26 
We now generate the same output as a script from photoxrepo. We should also test against Newton-X, I've opened a separate issue #67.
[Theodore](https://github.com/felixplasser/theodore-qc/blob/master/theodore/actions/spectrum.py) and SHARC does not seem to produce absolute cross sections.
> Fix intensity

- atmospec.ipynb
Depends on https://github.com/aiidalab/aiidalab-widgets-base/pull/340. This PR has been merged, but perhaps we should wait for the new AWB release before we merge this, otherwise our integration tests will keep failing.
> Add TrajectoryData to StructureBrowserWidget

- aiidalab_ispg/steps.py
- post_install
- setup.cfg
- workflows/aiidalab_atmospec_workchain/__init__.py
We temporarily switch to the latest develop branch so we can test out changes.
We should switch to stable version once there is a new release.
> Switch aiida-orca to develop branch

- aiidalab_ispg/spectrum.py
- aiidalab_ispg/steps.py
> Stick spectrum

- atmospec.ipynb
Use the AWB exception handler which catches uncaught exceptions and offers a link to open a new issue on Github.
Closes #94
> Automated bug reporting

- aiidalab_ispg/spectrum.py
- aiidalab_ispg/steps.py
- aiidalab_ispg/utils.py
- aiidalab_ispg/widgets.py
- workflows/aiidalab_atmospec_workchain/__init__.py
The current workflow design is not great,
and we need to awkwardly walk the call graph to extract the Gibbs free energies from the optimization workchains.
We need to refactor the workflow and add process labels to make this better. Unfortunately, that will be a breaking change.
Partly addresses #42, but will keep that issue open until the code is cleaned up. But the current version seems to work!
TODO
> Boltzmann-weighted spectra :tada: 

- aiidalab_ispg/spectrum.py
- spectrum_widget.ipynb
Turns out default value of traitlets is not None, which led to some issues in SpectrumWidget.
It's possible there are other bugs like this in other places.
> SpectrumWidget fixes

- workflow_workspace.ipynb
- workflows/aiidalab_atmospec_workchain/__init__.py
We change the `ConcatStructureIntoTrajectory` Workchain to a more lightweight `structures_to_trajectory` calcfunction. The new calcfunction also supports attaching arbitrary Array data though we do not use this functionality yet.
> calcfunction for constructing TrajectoryData

- aiidalab_ispg/parameters/orca.yaml
- aiidalab_ispg/steps.py
- tests/test_app.py
NOTE: We're copying over some code from AWB because we don't want to take AWB as a dependency for tests.
> Test steps' statuses more rigorously

- tests/conftest.py
- tests/test_app.py
TODO: Firefox somehow fails when checking multiple subsequent atom selection
> tests: refactor molecule fixtures

- tests/conftest.py
Hopefully might solve #118.
Closes #124
> Tests: Wait until the gear loading logo is invisible

- aiidalab_ispg/__init__.py
- aiidalab_ispg/atmospec_steps.py
- aiidalab_ispg/optimization_steps.py
- aiidalab_ispg/steps.py
- aiidalab_ispg/utils.py
Use the same base class as the OptimizationStep. Do not refactor do UI yet.
Closes #73
> Refactor Atmospec submission step

- aiidalab_ispg/spectrum.py
- aiidalab_ispg/spectrum_analysis.py
The current prototype is based on matplotlib and not fully working. I will merge this but this is currently disabled.
> Prototype: Energy vs Osc. Strength 2D density

- aiidalab_ispg/optimization_steps.py
- workflows/aiidalab_atmospec_workchain/optimization.py
Check for imaginary frequencies, immediately exit if any are detected. Step towards #8.
RobustOptimizationWorkChain now subclasses the OrcaBaseWorkChain, which reduces the workflow depth.
> Subclass OrcaBaseWorkChain by RobustOptimizationWorkChain

- README.md
- aiidalab_ispg/input_widgets.py
- atmospec.ipynb
> Add ERC funding attribution

- aiidalab_ispg/steps.py
- workflows/aiidalab_atmospec_workchain/optimization.py
Step towards finally solving #42
> Add energies and Boltzmann weights to TrajectoryData

- README.md
- setup.cfg
> Update AWB to stable v2.0.0

- aiidalab_ispg/app/atmospec_steps.py
- aiidalab_ispg/app/spectrum_analysis.py
- aiidalab_ispg/app/steps.py
- aiidalab_ispg/workflows/__init__.py
> Refactor atmospec workflow - - take 3

- .github/workflows/ci.yml
- pyproject.toml
Publish release notes when a new version is published
> GHA: Release notes

- aiidalab_ispg/app/qeapp/process.py
- aiidalab_ispg/app/widgets.py
We add extra info to the header: method/basis, label and description. Label and descriptions are optional fields of the input structure.
> Improve workchain selector header

- aiidalab_ispg/app/spectrum_analysis.py
- aiidalab_ispg/app/steps.py
- aiidalab_ispg/app/widgets.py
> Do not show calcfunctions in workflow tree

- aiidalab_ispg/app/atmospec_steps.py
- aiidalab_ispg/app/qeapp/process.py
- aiidalab_ispg/app/steps.py
- aiidalab_ispg/app/widgets.py
> Implement worklow status bar properly

- aiidalab_ispg/app/spectrum.py
Also, better re-rendering with sticks.
Fixes #201.
> SpectrumWidget: Fix stick spectrum

- notebooks/atmospec.ipynb
- notebooks/conformer_generation.ipynb
- notebooks/optimization.ipynb
- notebooks/spectrum_widget.ipynb
Also add friendly loading messages.
> Call load_profile in notebooks, don't rely on AWB

- .pre-commit-config.yaml
- aiidalab_ispg/app/__init__.py
- aiidalab_ispg/app/atmospec_steps.py
- aiidalab_ispg/app/conformers.py
- aiidalab_ispg/app/experimental_spectra/import_experimental_spectrum.py
- aiidalab_ispg/app/input_widgets.py
- aiidalab_ispg/app/optimization_steps.py
- aiidalab_ispg/app/qeapp/__init__.py
- aiidalab_ispg/app/qeapp/process.py
- aiidalab_ispg/app/qeapp/structures.py
- aiidalab_ispg/app/qeapp/widgets.py
- aiidalab_ispg/app/spectrum.py
- aiidalab_ispg/app/spectrum_analysis.py
- aiidalab_ispg/app/steps.py
- aiidalab_ispg/app/utils.py
- aiidalab_ispg/app/widgets.py
- aiidalab_ispg/workflows/atmospec.py
- aiidalab_ispg/workflows/harmonic_wigner.py
- aiidalab_ispg/workflows/optimization.py
- aiidalab_ispg/workflows/utils.py
- pyproject.toml
- tests/app/conftest.py
- tests/app/test_app.py
Sort imports, using the 'isort' rule implemented in ruff.
> Isort lint

- aiidalab_ispg/wigner/wigner.py
- pyproject.toml
Does not implement velocities yet
> Basic Wigner CLI

- aiidalab_ispg/app/spectrum.py
Should solve #236, but the current implementation is limited --- the cross sections of individual conformers will be downloaded only when they are displayed in the bokeh Figure when user clicks on "Show conformers". I will deal with this limitation in a separate PR since it will require a bit of code refactoring.
> Include conformer cross-sections in TSV download

- aiidalab_ispg/app/steps.py
Shamelessly stolen from https://github.com/aiidalab/aiidalab-qe/pull/500 (with some modifications).
> Add kill workflow button
